Replace `NcDateTimePicker` with `NcDateTimePickerNative`
nextcloud/calendar-availability-vue pull request #177
Opened 2023-11-07 17:45 UTC by JuliaKirschenheuter

Replace `NcDateTimePicker` with `NcDateTimePickerNative`

Fixes https://github.com/nextcloud/server/issues/40699

- Create accessible labels for input fields
- Fix other a11y issues (like closing a dropdown via `Esc`) via replacing components to `NcDateTimePickerNative`

### 🖼️ Screenshots

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2023-11-07 18-39-06](https://github.com/nextcloud/calendar-availability-vue/assets/6078378/31603229-a78c-4440-a727-c8b8bd0b0506) | ![Screenshot from 2023-11-07 18-38-54](https://github.com/nextcloud/calendar-availability-vue/assets/6078378/b10c6551-b879-4995-95b4-83faa045be10)

2023-11-07 18:05 UTC, Pytal approved these changes
Other than translations

2023-11-07 18:05 UTC, Pytal commented on src/CalendarAvailability.vue
> +								:label="`Pick a start time for ${day.displayName}`"
Needs to be translated

2023-11-07 18:05 UTC, Pytal commented on src/CalendarAvailability.vue
> +								:label="`Pick a end time for ${day.displayName}`"
Translation needed

2023-11-08 01:49 UTC, susnux approved these changes

2023-11-08 09:01 UTC, susnux requested changes

2023-11-08 09:01 UTC, susnux commented on src/CalendarAvailability.vue
> +								:label="$t('dav', `Pick a start time for ${day.displayName}`)"
```suggestion
								:label="t('dav', 'Pick a start time for {dayName}', { dayName: day.displayName })"
```

2023-11-08 09:01 UTC, susnux commented on src/CalendarAvailability.vue
> +								:label="$t('dav', `Pick a end time for ${day.displayName}`)"
```suggestion
								:label="t('dav', 'Pick a end time for {dayName}', { dayName: day.displayName })"
```

2023-11-08 10:09 UTC, ShGKme commented
This library doesn't have any built-in l10n support at all. 

It supposes a user to pass all localized strings as props (like `l10nMonday`).

**Simple solution**

Add new props aka `l10nStartPickerLabel` and pass translated strings from the server/calendar where the component is used. And the value should be not a translation, but a function. Aka
```js
(dayName) => t('dav', 'Pick a start time for {dayName}', { dayName })
```
And then it can be used as
```html
:label="l10nStartPickerLabel(day.displayName)"
```

**Complex solution**

Set up l10n for the library. Example: https://github.com/nextcloud-libraries/nextcloud-password-confirmation

**Alternative solution**

Move this component to the `nextcloud/vue`. To be honest, I don't see why it should be an individual package and repository.

2023-11-08 16:09 UTC, ShGKme approved these changes

2023-11-08 16:10 UTC, susnux approved these changes

2023-11-08 16:23 UTC, st3iny approved these changes
Tested and works. Thanks :)

2023-11-08 16:31 UTC, merged