Add Eslint to project
nextcloud/calendar-availability-vue pull request #18
Opened 2022-02-22 12:55 UTC by JuliaKirschenheuter

Add Eslint
Add first config files

2022-02-22 12:59 UTC, JuliaKirschenheuter commented
@skjnldsv i would like to ask you about this configuration. ESLint is working, but if i run `npm run lint:fix` i have 9 errors:
`'logger' is not defined  no-undef`
and 8 of them `'ICAL' is not defined `

please let me know if  you have some idea, how could i fix it.
Thank you!

2022-02-22 13:01 UTC, ChristophWurst commented
The missing logger can be fixed by adding https://github.com/nextcloud/nextcloud-logger/ to this project similar to https://github.com/nextcloud/mail/blob/main/src/logger.js

The ICAL error is weird. We use `ical.js` for the import.

2022-02-22 14:44 UTC, ChristophWurst commented on src/utils/logger.js
> +	.setApp('@nextcloud/vue')
```suggestion
	.setApp('@nextcloud/calendar-availability-vue')
```

2022-06-29 11:34 UTC, ChristophWurst requested changes

2022-06-29 11:34 UTC, ChristophWurst commented on .eslintrc.js
> +		appVersion: true,
we don't use any of this, do we?

2022-06-29 11:34 UTC, ChristophWurst commented on .github/workflows/lint.yml
> +        run: composer run lint
there are no php files

2022-06-29 11:34 UTC, ChristophWurst commented on .github/workflows/lint.yml
> +        run: composer run cs:check
only relevant for php

2022-06-29 15:54 UTC, skjnldsv commented
@JuliaKirschenheuter please use the lin templates from https://github.com/nextcloud/.github

2022-06-29 15:56 UTC, skjnldsv commented
> The ICAL error is weird. We use `ical.js` for the import at

I was about to write 
> iirc the ICAL pollute window and uses it.
> Make sure it's defiend as a global 

But I realised contacts works fine without :thinking: https://github.com/nextcloud/contacts/blob/9d1a7cf81a5420ddb9d6ea8961931d046b3e6e2b/.eslintrc.js#L2-L5
So I guess it's something else

2023-01-11 14:10 UTC, st3iny commented on stylelint.config.js
> +const stylelintConfig = require('@nextcloud/stylelint-config')
Done

2023-01-11 14:10 UTC, st3iny commented on package.json
> +    "vue-loader": "^15.9.8",
Done

2023-01-11 14:10 UTC, st3iny commented on package.json
> +    "stylelint:fix": "stylelint src/**/*.vue src/**/*.scss src/**/*.css --fix"
Done

2023-01-11 14:10 UTC, st3iny commented on .stylelintignore
> +/src/fonts
Done

2023-01-11 14:10 UTC, st3iny commented on .github/workflows/lint.yml
> +        run: composer run cs:check
Done

2023-01-11 14:10 UTC, st3iny commented on .github/workflows/lint.yml
> +          xml-schema-file: ./info.xsd
Done

2023-01-11 14:32 UTC, ChristophWurst approved these changes
:shipit:

2023-01-11 14:32 UTC, merged